DROP TABLE ITEM CASCADE CONSTRAINTS;

DROP TABLE LOGGING_EVENT CASCADE CONSTRAINTS;

DROP TABLE LOGGING_EVENT_EXCEPTION CASCADE CONSTRAINTS;

DROP TABLE LOGGING_EVENT_PROPERTY CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_ARTICLE CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_ATTACH_FILE CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_BOARD CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_CDDTL CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_CDMST CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_COMMENT CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_MENU CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_MENU_ROLE_MAP CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_MSG CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_PRGM CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_PRGM_ROLE_MAP CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_ROLE CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_ROLE_USER_MAP CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_USER CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_USER_GRP CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_USER_GRP_USER_MAP CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_VIEW_ELEMENT CASCADE CONSTRAINTS;

DROP TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP CASCADE CONSTRAINTS;

DROP SEQUENCE HIBERNATE_SEQUENCE;

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE ITEM (
    ITEM_ID NUMBER(19,0) NOT NULL,
    ITEM_DESC VARCHAR2(255 CHAR),
    ITEM_NAME VARCHAR2(255 CHAR),
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE LOGGING_EVENT (
    EVENT_ID NUMBER(19,0) NOT NULL,
    ARG0 VARCHAR2(254 CHAR),
    ARG1 VARCHAR2(254 CHAR),
    ARG2 VARCHAR2(254 CHAR),
    ARG3 VARCHAR2(254 CHAR),
    CALLER_CLASS VARCHAR2(254 CHAR),
    CALLER_FILENAME VARCHAR2(254 CHAR),
    CALLER_LINE VARCHAR2(255 CHAR),
    CALLER_METHOD VARCHAR2(254 CHAR),
    FORMATTED_MESSAGE VARCHAR2(4000 CHAR),
    LEVEL_STRING VARCHAR2(254 CHAR),
    LOGGER_NAME VARCHAR2(254 CHAR),
    REFERENCE_FLAG NUMBER(10,0),
    THREAD_NAME VARCHAR2(254 CHAR),
    TIMESTMP NUMBER(19,0) NOT NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE LOGGING_EVENT_EXCEPTION (
    I NUMBER(10,0) NOT NULL,
    TRACE_LINE VARCHAR2(254 CHAR) NOT NULL,
    EVENT_ID NUMBER(19,0),
    PRIMARY KEY (I)
);

CREATE TABLE LOGGING_EVENT_PROPERTY (
    EVENT_ID NUMBER(19,0) NOT NULL,
    MAPPED_KEY VARCHAR2(254 CHAR) NOT NULL,
    MAPPED_VALUE VARCHAR2(1024 CHAR) NOT NULL,
    PRIMARY KEY (EVENT_ID, MAPPED_KEY)
);

CREATE TABLE TB_BCM_ARTICLE (
    ARTICLE_ID NUMBER(19,0) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    ARTICLE_BEGIN_DT VARCHAR2(8 CHAR),
    ARTICLE_CTNT CLOB NOT NULL,
    ARTICLE_END_DT VARCHAR2(8 CHAR),
    ARTICLE_TITLE VARCHAR2(128 CHAR) NOT NULL,
    ARTICLE_TYP VARCHAR2(50 CHAR) NOT NULL,
    EMGC_YN CHAR(1 CHAR) NOT NULL,
    HIT_CNT NUMBER(10,0) NOT NULL,
    BOARD_ID VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ARTICLE_ID)
);

CREATE TABLE TB_BCM_ATTACH_FILE (
    FILE_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    FILE_EXT VARCHAR2(10 CHAR) NOT NULL,
    FILE_PATH VARCHAR2(200 CHAR) NOT NULL,
    FILE_SIZE NUMBER(19,0) NOT NULL,
    ORI_FILE_NM VARCHAR2(200 CHAR) NOT NULL,
    SVR_FILE_NM VARCHAR2(200 CHAR) NOT NULL,
    TARGET_ID VARCHAR2(50 CHAR) NOT NULL,
    TARGET_TYP VARCHAR2(50 CHAR) NOT NULL,
    PRIMARY KEY (FILE_ID)
);

CREATE TABLE TB_BCM_BOARD (
    BOARD_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    ATTACH_FILE_TYP VARCHAR2(50 CHAR) NOT NULL,
    BASE_PATH VARCHAR2(1000 CHAR) NOT NULL,
    BOARD_DESC VARCHAR2(2000 CHAR),
    BOARD_NM VARCHAR2(128 CHAR) NOT NULL,
    BOARD_TYP VARCHAR2(50 CHAR) NOT NULL,
    COMMENT_USE_YN CHAR(1 CHAR) NOT NULL,
    EMGC_USE_YN CHAR(1 CHAR) NOT NULL,
    TERM_USE_YN CHAR(1 CHAR) NOT NULL,
    PRIMARY KEY (BOARD_ID)
);

CREATE TABLE TB_BCM_CDDTL (
    CD_ID VARCHAR2(255 CHAR) NOT NULL,
    CD_DTL_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    CD_DTL_DESC VARCHAR2(2000 CHAR),
    CD_DTL_NM1 VARCHAR2(128 CHAR),
    CD_DTL_NM2 VARCHAR2(128 CHAR),
    CD_DTL_NM3 VARCHAR2(128 CHAR),
    CD_SORT_SEQ NUMBER(10,0),
    PRIMARY KEY (CD_ID, CD_DTL_ID)
);

CREATE TABLE TB_BCM_CDMST (
    CD_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    CD_DESC VARCHAR2(2000 CHAR),
    CD_NM1 VARCHAR2(128 CHAR),
    CD_NM2 VARCHAR2(128 CHAR),
    CD_NM3 VARCHAR2(128 CHAR),
    PRIMARY KEY (CD_ID)
);

CREATE TABLE TB_BCM_COMMENT (
    COMMENT_ID NUMBER(19,0) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    COMMENT_CTNT VARCHAR2(1000 CHAR) NOT NULL,
    ARTICLE_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (COMMENT_ID)
);

CREATE TABLE TB_BCM_MENU (
    MENU_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    MENU_DESC VARCHAR2(2000 CHAR),
    MENU_NM1 VARCHAR2(128 CHAR) NOT NULL,
    MENU_NM2 VARCHAR2(128 CHAR),
    MENU_NM3 VARCHAR2(128 CHAR),
    MENU_SORT_SEQ NUMBER(10,0) NOT NULL,
    MENU_TYP VARCHAR2(50 CHAR) NOT NULL,
    OPEN_TYP VARCHAR2(1 CHAR),
    PARENT_MENU_ID VARCHAR2(10 CHAR) NOT NULL,
    URL_ADDR VARCHAR2(1000 CHAR),
    PRGM_ID VARCHAR2(255 CHAR),
    PRIMARY KEY (MENU_ID)
);

CREATE TABLE TB_BCM_MENU_ROLE_MAP (
    MENU_ID VARCHAR2(255 CHAR) NOT NULL,
    ROLE_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    PRIMARY KEY (MENU_ID, ROLE_ID)
);

CREATE TABLE TB_BCM_MSG (
    MSG_KEY VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    MSG_DESC VARCHAR2(2000 CHAR),
    MSG_NM1 VARCHAR2(2000 CHAR),
    MSG_NM2 VARCHAR2(2000 CHAR),
    MSG_NM3 VARCHAR2(2000 CHAR),
    TARGET VARCHAR2(128 CHAR) NOT NULL,
    PRIMARY KEY (MSG_KEY)
);

CREATE TABLE TB_BCM_PRGM (
    PRGM_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    BASE_PATH VARCHAR2(1000 CHAR),
    HTTP_METHOD VARCHAR2(10 CHAR) NOT NULL,
    PRGM_DESC VARCHAR2(2000 CHAR),
    PRGM_NM VARCHAR2(128 CHAR) NOT NULL,
    PRGM_PATH VARCHAR2(1000 CHAR) NOT NULL,
    PRGM_TYP VARCHAR2(50 CHAR) NOT NULL,
    PRIMARY KEY (PRGM_ID)
);

CREATE TABLE TB_BCM_PRGM_ROLE_MAP (
    PRGM_ID VARCHAR2(255 CHAR) NOT NULL,
    ROLE_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    PRIMARY KEY (PRGM_ID, ROLE_ID)
);

CREATE TABLE TB_BCM_ROLE (
    ROLE_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    ROLE_DESC VARCHAR2(2000 CHAR),
    ROLE_NM VARCHAR2(128 CHAR) NOT NULL,
    ROLE_TYP VARCHAR2(50 CHAR) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE TB_BCM_ROLE_USER_MAP (
    ROLE_SEQ NUMBER(19,0) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    ROLE_BEGIN_DT VARCHAR2(8 CHAR) NOT NULL,
    ROLE_END_DT VARCHAR2(8 CHAR) NOT NULL,
    ROLE_ID VARCHAR2(255 CHAR),
    USER_ID VARCHAR2(255 CHAR),
    USER_GRP_ID VARCHAR2(255 CHAR),
    PRIMARY KEY (ROLE_SEQ)
);

CREATE TABLE TB_BCM_USER (
    USER_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    COMP_CD VARCHAR2(20 CHAR) NOT NULL,
    DEPT_NM VARCHAR2(128 CHAR),
    EMAIL_ADDR VARCHAR2(128 CHAR) NOT NULL,
    FIRST_LOGIN_YN CHAR(1 CHAR) NOT NULL,
    GW_IF_YN CHAR(1 CHAR) NOT NULL,
    LAST_PWD_CHG_DTM TIMESTAMP,
    LOGIN_FAIL_CNT NUMBER(10,0) NOT NULL,
    LOGIN_ID VARCHAR2(36 CHAR) NOT NULL,
    MOBILE_NO VARCHAR2(20 CHAR),
    PWD VARCHAR2(128 CHAR) NOT NULL,
    POSITION_NM VARCHAR2(128 CHAR),
    REGULAR_YN CHAR(1 CHAR) NOT NULL,
    SSO_YN CHAR(1 CHAR) NOT NULL,
    TEL_NO VARCHAR2(20 CHAR),
    USER_NM VARCHAR2(128 CHAR) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE TB_BCM_USER_GRP (
    USER_GRP_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    COMP_CD VARCHAR2(20 CHAR),
    USER_GRP_DESC VARCHAR2(2000 CHAR),
    USER_GRP_NM VARCHAR2(128 CHAR) NOT NULL,
    PRIMARY KEY (USER_GRP_ID)
);

CREATE TABLE TB_BCM_USER_GRP_USER_MAP (
    USER_GRP_ID VARCHAR2(255 CHAR) NOT NULL,
    USER_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    PRIMARY KEY (USER_GRP_ID, USER_ID)
);

CREATE TABLE TB_BCM_VIEW_ELEMENT (
    ELEMENT_SEQ NUMBER(19,0) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    USE_YN CHAR(1 CHAR) NOT NULL,
    ELEMENT_DESC VARCHAR2(2000 CHAR),
    ELEMENT_KEY VARCHAR2(128 CHAR) NOT NULL,
    PRGM_ID VARCHAR2(255 CHAR),
    PRIMARY KEY (ELEMENT_SEQ)
);

CREATE TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP (
    ELEMENT_SEQ NUMBER(19,0) NOT NULL,
    ROLE_ID VARCHAR2(255 CHAR) NOT NULL,
    REG_USER_ID VARCHAR2(36 CHAR),
    REG_DTM TIMESTAMP,
    UPD_USER_ID VARCHAR2(36 CHAR),
    UPD_DTM TIMESTAMP,
    ENABLE_YN CHAR(1 CHAR),
    VISIBLE_YN CHAR(1 CHAR),
    PRIMARY KEY (ELEMENT_SEQ, ROLE_ID)
);

ALTER TABLE TB_BCM_USER 
    ADD CONSTRAINT UK_BH0F4I8SA5W1HCK72DC4OLQ0V UNIQUE (LOGIN_ID);

ALTER TABLE LOGGING_EVENT_EXCEPTION 
    ADD CONSTRAINT FK5SHA06UOH5SO48G4YSCTVB6WQ 
    FOREIGN KEY (EVENT_ID) 
    REFERENCES LOGGING_EVENT;

ALTER TABLE LOGGING_EVENT_PROPERTY 
    ADD CONSTRAINT FK8LPNRJABYMV2AL942NJAU5O93 
    FOREIGN KEY (EVENT_ID) 
    REFERENCES LOGGING_EVENT;

ALTER TABLE TB_BCM_ARTICLE 
    ADD CONSTRAINT FKIBDSCQTNRWWTLCCK31IXPIMJ8 
    FOREIGN KEY (BOARD_ID) 
    REFERENCES TB_BCM_BOARD;

ALTER TABLE TB_BCM_CDDTL 
    ADD CONSTRAINT FKA3J15XD8JHXIY0LH4BA6E564X 
    FOREIGN KEY (CD_ID) 
    REFERENCES TB_BCM_CDMST;

ALTER TABLE TB_BCM_COMMENT 
    ADD CONSTRAINT FK8RC6771GO066P7REKM44F1RDW 
    FOREIGN KEY (ARTICLE_ID) 
    REFERENCES TB_BCM_ARTICLE;

ALTER TABLE TB_BCM_MENU 
    ADD CONSTRAINT FK9E1WFXEYRYO2JCNHIRWTSOKO7 
    FOREIGN KEY (PRGM_ID) 
    REFERENCES TB_BCM_PRGM;

ALTER TABLE TB_BCM_MENU_ROLE_MAP 
    ADD CONSTRAINT FKMMDTYISWMTDHLNN4R4Q8LO9W4 
    FOREIGN KEY (MENU_ID) 
    REFERENCES TB_BCM_MENU;

ALTER TABLE TB_BCM_MENU_ROLE_MAP 
    ADD CONSTRAINT FKIRF7XUUFYJ3P9RPTB4GC7UWWG 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;

ALTER TABLE TB_BCM_PRGM_ROLE_MAP 
    ADD CONSTRAINT FKMUKLBGPKNNYJ79FHQW50K1528 
    FOREIGN KEY (PRGM_ID) 
    REFERENCES TB_BCM_PRGM;

ALTER TABLE TB_BCM_PRGM_ROLE_MAP 
    ADD CONSTRAINT FKR3TUIOBIBMDL625NRA1FQAU2Q 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    ADD CONSTRAINT FKUKJU3G6WVQCKU257YI8LAWB6 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    ADD CONSTRAINT FKOME08SVK3S2RRHQ28BTBY4DGA 
    FOREIGN KEY (USER_ID) 
    REFERENCES TB_BCM_USER;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    ADD CONSTRAINT FKOPTU2LN8KNEIH9YHX6VGWPNDY 
    FOREIGN KEY (USER_GRP_ID) 
    REFERENCES TB_BCM_USER_GRP;

ALTER TABLE TB_BCM_USER_GRP_USER_MAP 
    ADD CONSTRAINT FKT5X8BF0946DJ4U2JMJOI9AG0L 
    FOREIGN KEY (USER_ID) 
    REFERENCES TB_BCM_USER;

ALTER TABLE TB_BCM_USER_GRP_USER_MAP 
    ADD CONSTRAINT FKNCFEDB3QWGEVL4RB6834HFGTJ 
    FOREIGN KEY (USER_GRP_ID) 
    REFERENCES TB_BCM_USER_GRP;

ALTER TABLE TB_BCM_VIEW_ELEMENT 
    ADD CONSTRAINT FK3E76S446RI8AS9K3CWDLH4MO9 
    FOREIGN KEY (PRGM_ID) 
    REFERENCES TB_BCM_PRGM;

ALTER TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP 
    ADD CONSTRAINT FKCEP99MAKY2VIAWCANAQ28WCQW 
    FOREIGN KEY (ELEMENT_SEQ) 
    REFERENCES TB_BCM_VIEW_ELEMENT;

ALTER TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP 
    ADD CONSTRAINT FKOPHSW4F873NLC276W3OCGR59E 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;
  
DROP TRIGGER logging_event_id_seq_trig; 
DROP SEQUENCE logging_event_id_seq; 

CREATE SEQUENCE logging_event_id_seq MINVALUE 1 START WITH 1;

CREATE TRIGGER logging_event_id_seq_trig
  BEFORE INSERT ON logging_event
  FOR EACH ROW  
  BEGIN  
    SELECT logging_event_id_seq.NEXTVAL 
    INTO   :NEW.event_id 
    FROM   DUAL;  
  END;
/
