ALTER TABLE LOGGING_EVENT_EXCEPTION 
    DROP CONSTRAINT FK5SHA06UOH5SO48G4YSCTVB6WQ;

ALTER TABLE LOGGING_EVENT_PROPERTY 
    DROP CONSTRAINT FK8LPNRJABYMV2AL942NJAU5O93;

ALTER TABLE TB_BCM_ARTICLE 
    DROP CONSTRAINT FKIBDSCQTNRWWTLCCK31IXPIMJ8;

ALTER TABLE TB_BCM_CDDTL 
    DROP CONSTRAINT FKA3J15XD8JHXIY0LH4BA6E564X;

ALTER TABLE TB_BCM_COMMENT 
    DROP CONSTRAINT FK8RC6771GO066P7REKM44F1RDW;

ALTER TABLE TB_BCM_MENU 
    DROP CONSTRAINT FK9E1WFXEYRYO2JCNHIRWTSOKO7;

ALTER TABLE TB_BCM_MENU_ROLE_MAP 
    DROP CONSTRAINT FKMMDTYISWMTDHLNN4R4Q8LO9W4;

ALTER TABLE TB_BCM_MENU_ROLE_MAP 
    DROP CONSTRAINT FKIRF7XUUFYJ3P9RPTB4GC7UWWG;

ALTER TABLE TB_BCM_PRGM_ROLE_MAP 
    DROP CONSTRAINT FKMUKLBGPKNNYJ79FHQW50K1528;

ALTER TABLE TB_BCM_PRGM_ROLE_MAP 
    DROP CONSTRAINT FKR3TUIOBIBMDL625NRA1FQAU2Q;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    DROP CONSTRAINT FKUKJU3G6WVQCKU257YI8LAWB6;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    DROP CONSTRAINT FKOME08SVK3S2RRHQ28BTBY4DGA;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    DROP CONSTRAINT FKOPTU2LN8KNEIH9YHX6VGWPNDY;

ALTER TABLE TB_BCM_USER_GRP_USER_MAP 
    DROP CONSTRAINT FKT5X8BF0946DJ4U2JMJOI9AG0L;

ALTER TABLE TB_BCM_USER_GRP_USER_MAP 
    DROP CONSTRAINT FKNCFEDB3QWGEVL4RB6834HFGTJ;

ALTER TABLE TB_BCM_VIEW_ELEMENT 
    DROP CONSTRAINT FK3E76S446RI8AS9K3CWDLH4MO9;

ALTER TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP 
    DROP CONSTRAINT FKCEP99MAKY2VIAWCANAQ28WCQW;

ALTER TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP 
    DROP CONSTRAINT FKOPHSW4F873NLC276W3OCGR59E;

DROP TABLE ITEM;

DROP TABLE LOGGING_EVENT;

DROP TABLE LOGGING_EVENT_EXCEPTION;

DROP TABLE LOGGING_EVENT_PROPERTY;

DROP TABLE TB_BCM_ARTICLE;

DROP TABLE TB_BCM_ATTACH_FILE;

DROP TABLE TB_BCM_BOARD;

DROP TABLE TB_BCM_CDDTL;

DROP TABLE TB_BCM_CDMST;

DROP TABLE TB_BCM_COMMENT;

DROP TABLE TB_BCM_MENU;

DROP TABLE TB_BCM_MENU_ROLE_MAP;

DROP TABLE TB_BCM_MSG;

DROP TABLE TB_BCM_PRGM;

DROP TABLE TB_BCM_PRGM_ROLE_MAP;

DROP TABLE TB_BCM_ROLE;

DROP TABLE TB_BCM_ROLE_USER_MAP;

DROP TABLE TB_BCM_USER;

DROP TABLE TB_BCM_USER_GRP;

DROP TABLE TB_BCM_USER_GRP_USER_MAP;

DROP TABLE TB_BCM_VIEW_ELEMENT;

DROP TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP;

CREATE TABLE ITEM (
    ITEM_ID BIGINT NOT NULL,
    ITEM_DESC VARCHAR(255),
    ITEM_NAME VARCHAR(255),
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE LOGGING_EVENT (
    EVENT_ID BIGINT IDENTITY NOT NULL,
    ARG0 VARCHAR(254),
    ARG1 VARCHAR(254),
    ARG2 VARCHAR(254),
    ARG3 VARCHAR(254),
    CALLER_CLASS VARCHAR(254),
    CALLER_FILENAME VARCHAR(254),
    CALLER_LINE VARCHAR(255),
    CALLER_METHOD VARCHAR(254),
    FORMATTED_MESSAGE VARCHAR(4000),
    LEVEL_STRING VARCHAR(254),
    LOGGER_NAME VARCHAR(254),
    REFERENCE_FLAG INT,
    THREAD_NAME VARCHAR(254),
    TIMESTMP BIGINT NOT NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE LOGGING_EVENT_EXCEPTION (
    I INT NOT NULL,
    TRACE_LINE VARCHAR(254) NOT NULL,
    EVENT_ID BIGINT,
    PRIMARY KEY (I)
);

CREATE TABLE LOGGING_EVENT_PROPERTY (
    EVENT_ID BIGINT NOT NULL,
    MAPPED_KEY VARCHAR(254) NOT NULL,
    MAPPED_VALUE VARCHAR(1024) NOT NULL,
    PRIMARY KEY (EVENT_ID, MAPPED_KEY)
);

CREATE TABLE TB_BCM_ARTICLE (
    ARTICLE_ID BIGINT IDENTITY NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    ARTICLE_BEGIN_DT VARCHAR(8),
    ARTICLE_CTNT VARCHAR(MAX) NOT NULL,
    ARTICLE_END_DT VARCHAR(8),
    ARTICLE_TITLE VARCHAR(128) NOT NULL,
    ARTICLE_TYP VARCHAR(50) NOT NULL,
    EMGC_YN CHAR(1) NOT NULL,
    HIT_CNT INT NOT NULL,
    BOARD_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ARTICLE_ID)
);

CREATE TABLE TB_BCM_ATTACH_FILE (
    FILE_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    FILE_EXT VARCHAR(10) NOT NULL,
    FILE_PATH VARCHAR(200) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    ORI_FILE_NM VARCHAR(200) NOT NULL,
    SVR_FILE_NM VARCHAR(200) NOT NULL,
    TARGET_ID VARCHAR(50) NOT NULL,
    TARGET_TYP VARCHAR(50) NOT NULL,
    PRIMARY KEY (FILE_ID)
);

CREATE TABLE TB_BCM_BOARD (
    BOARD_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    ATTACH_FILE_TYP VARCHAR(50) NOT NULL,
    BASE_PATH VARCHAR(1000) NOT NULL,
    BOARD_DESC VARCHAR(2000),
    BOARD_NM VARCHAR(128) NOT NULL,
    BOARD_TYP VARCHAR(50) NOT NULL,
    COMMENT_USE_YN CHAR(1) NOT NULL,
    EMGC_USE_YN CHAR(1) NOT NULL,
    TERM_USE_YN CHAR(1) NOT NULL,
    PRIMARY KEY (BOARD_ID)
);

CREATE TABLE TB_BCM_CDDTL (
    CD_ID VARCHAR(255) NOT NULL,
    CD_DTL_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    CD_DTL_DESC VARCHAR(2000),
    CD_DTL_NM1 VARCHAR(128),
    CD_DTL_NM2 VARCHAR(128),
    CD_DTL_NM3 VARCHAR(128),
    CD_SORT_SEQ INT,
    PRIMARY KEY (CD_ID, CD_DTL_ID)
);

CREATE TABLE TB_BCM_CDMST (
    CD_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    CD_DESC VARCHAR(2000),
    CD_NM1 VARCHAR(128),
    CD_NM2 VARCHAR(128),
    CD_NM3 VARCHAR(128),
    PRIMARY KEY (CD_ID)
);

CREATE TABLE TB_BCM_COMMENT (
    COMMENT_ID BIGINT IDENTITY NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    COMMENT_CTNT VARCHAR(1000) NOT NULL,
    ARTICLE_ID BIGINT NOT NULL,
    PRIMARY KEY (COMMENT_ID)
);

CREATE TABLE TB_BCM_MENU (
    MENU_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    MENU_DESC VARCHAR(2000),
    MENU_NM1 VARCHAR(128) NOT NULL,
    MENU_NM2 VARCHAR(128),
    MENU_NM3 VARCHAR(128),
    MENU_SORT_SEQ INT NOT NULL,
    MENU_TYP VARCHAR(50) NOT NULL,
    OPEN_TYP VARCHAR(1),
    PARENT_MENU_ID VARCHAR(10) NOT NULL,
    URL_ADDR VARCHAR(1000),
    PRGM_ID VARCHAR(255),
    PRIMARY KEY (MENU_ID)
);

CREATE TABLE TB_BCM_MENU_ROLE_MAP (
    MENU_ID VARCHAR(255) NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    PRIMARY KEY (MENU_ID, ROLE_ID)
);

CREATE TABLE TB_BCM_MSG (
    MSG_KEY VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    MSG_DESC VARCHAR(2000),
    MSG_NM1 VARCHAR(2000),
    MSG_NM2 VARCHAR(2000),
    MSG_NM3 VARCHAR(2000),
    TARGET VARCHAR(128) NOT NULL,
    PRIMARY KEY (MSG_KEY)
);

CREATE TABLE TB_BCM_PRGM (
    PRGM_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    BASE_PATH VARCHAR(1000),
    HTTP_METHOD VARCHAR(10) NOT NULL,
    PRGM_DESC VARCHAR(2000),
    PRGM_NM VARCHAR(128) NOT NULL,
    PRGM_PATH VARCHAR(1000) NOT NULL,
    PRGM_TYP VARCHAR(50) NOT NULL,
    PRIMARY KEY (PRGM_ID)
);

CREATE TABLE TB_BCM_PRGM_ROLE_MAP (
    PRGM_ID VARCHAR(255) NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    PRIMARY KEY (PRGM_ID, ROLE_ID)
);

CREATE TABLE TB_BCM_ROLE (
    ROLE_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    ROLE_DESC VARCHAR(2000),
    ROLE_NM VARCHAR(128) NOT NULL,
    ROLE_TYP VARCHAR(50) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE TB_BCM_ROLE_USER_MAP (
    ROLE_SEQ BIGINT IDENTITY NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    ROLE_BEGIN_DT VARCHAR(8) NOT NULL,
    ROLE_END_DT VARCHAR(8) NOT NULL,
    ROLE_ID VARCHAR(255),
    USER_ID VARCHAR(255),
    USER_GRP_ID VARCHAR(255),
    PRIMARY KEY (ROLE_SEQ)
);

CREATE TABLE TB_BCM_USER (
    USER_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    COMP_CD VARCHAR(20) NOT NULL,
    DEPT_NM VARCHAR(128),
    EMAIL_ADDR VARCHAR(128) NOT NULL,
    FIRST_LOGIN_YN CHAR(1) NOT NULL,
    GW_IF_YN CHAR(1) NOT NULL,
    LAST_PWD_CHG_DTM DATETIME2,
    LOGIN_FAIL_CNT INT NOT NULL,
    LOGIN_ID VARCHAR(36) NOT NULL,
    MOBILE_NO VARCHAR(20),
    PWD VARCHAR(128) NOT NULL,
    POSITION_NM VARCHAR(128),
    REGULAR_YN CHAR(1) NOT NULL,
    SSO_YN CHAR(1) NOT NULL,
    TEL_NO VARCHAR(20),
    USER_NM VARCHAR(128) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE TB_BCM_USER_GRP (
    USER_GRP_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    COMP_CD VARCHAR(20),
    USER_GRP_DESC VARCHAR(2000),
    USER_GRP_NM VARCHAR(128) NOT NULL,
    PRIMARY KEY (USER_GRP_ID)
);

CREATE TABLE TB_BCM_USER_GRP_USER_MAP (
    USER_GRP_ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    PRIMARY KEY (USER_GRP_ID, USER_ID)
);

CREATE TABLE TB_BCM_VIEW_ELEMENT (
    ELEMENT_SEQ BIGINT IDENTITY NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    USE_YN CHAR(1) NOT NULL,
    ELEMENT_DESC VARCHAR(2000),
    ELEMENT_KEY VARCHAR(128) NOT NULL,
    PRGM_ID VARCHAR(255),
    PRIMARY KEY (ELEMENT_SEQ)
);

CREATE TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP (
    ELEMENT_SEQ BIGINT NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    REG_USER_ID VARCHAR(36),
    REG_DTM DATETIME2,
    UPD_USER_ID VARCHAR(36),
    UPD_DTM DATETIME2,
    ENABLE_YN CHAR(1),
    VISIBLE_YN CHAR(1),
    PRIMARY KEY (ELEMENT_SEQ, ROLE_ID)
);

ALTER TABLE TB_BCM_USER 
    ADD CONSTRAINT UK_BH0F4I8SA5W1HCK72DC4OLQ0V UNIQUE (LOGIN_ID);

ALTER TABLE LOGGING_EVENT_EXCEPTION 
    ADD CONSTRAINT FK5SHA06UOH5SO48G4YSCTVB6WQ 
    FOREIGN KEY (EVENT_ID) 
    REFERENCES LOGGING_EVENT;

ALTER TABLE LOGGING_EVENT_PROPERTY 
    ADD CONSTRAINT FK8LPNRJABYMV2AL942NJAU5O93 
    FOREIGN KEY (EVENT_ID) 
    REFERENCES LOGGING_EVENT;

ALTER TABLE TB_BCM_ARTICLE 
    ADD CONSTRAINT FKIBDSCQTNRWWTLCCK31IXPIMJ8 
    FOREIGN KEY (BOARD_ID) 
    REFERENCES TB_BCM_BOARD;

ALTER TABLE TB_BCM_CDDTL 
    ADD CONSTRAINT FKA3J15XD8JHXIY0LH4BA6E564X 
    FOREIGN KEY (CD_ID) 
    REFERENCES TB_BCM_CDMST;

ALTER TABLE TB_BCM_COMMENT 
    ADD CONSTRAINT FK8RC6771GO066P7REKM44F1RDW 
    FOREIGN KEY (ARTICLE_ID) 
    REFERENCES TB_BCM_ARTICLE;

ALTER TABLE TB_BCM_MENU 
    ADD CONSTRAINT FK9E1WFXEYRYO2JCNHIRWTSOKO7 
    FOREIGN KEY (PRGM_ID) 
    REFERENCES TB_BCM_PRGM;

ALTER TABLE TB_BCM_MENU_ROLE_MAP 
    ADD CONSTRAINT FKMMDTYISWMTDHLNN4R4Q8LO9W4 
    FOREIGN KEY (MENU_ID) 
    REFERENCES TB_BCM_MENU;

ALTER TABLE TB_BCM_MENU_ROLE_MAP 
    ADD CONSTRAINT FKIRF7XUUFYJ3P9RPTB4GC7UWWG 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;

ALTER TABLE TB_BCM_PRGM_ROLE_MAP 
    ADD CONSTRAINT FKMUKLBGPKNNYJ79FHQW50K1528 
    FOREIGN KEY (PRGM_ID) 
    REFERENCES TB_BCM_PRGM;

ALTER TABLE TB_BCM_PRGM_ROLE_MAP 
    ADD CONSTRAINT FKR3TUIOBIBMDL625NRA1FQAU2Q 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    ADD CONSTRAINT FKUKJU3G6WVQCKU257YI8LAWB6 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    ADD CONSTRAINT FKOME08SVK3S2RRHQ28BTBY4DGA 
    FOREIGN KEY (USER_ID) 
    REFERENCES TB_BCM_USER;

ALTER TABLE TB_BCM_ROLE_USER_MAP 
    ADD CONSTRAINT FKOPTU2LN8KNEIH9YHX6VGWPNDY 
    FOREIGN KEY (USER_GRP_ID) 
    REFERENCES TB_BCM_USER_GRP;

ALTER TABLE TB_BCM_USER_GRP_USER_MAP 
    ADD CONSTRAINT FKT5X8BF0946DJ4U2JMJOI9AG0L 
    FOREIGN KEY (USER_ID) 
    REFERENCES TB_BCM_USER;

ALTER TABLE TB_BCM_USER_GRP_USER_MAP 
    ADD CONSTRAINT FKNCFEDB3QWGEVL4RB6834HFGTJ 
    FOREIGN KEY (USER_GRP_ID) 
    REFERENCES TB_BCM_USER_GRP;

ALTER TABLE TB_BCM_VIEW_ELEMENT 
    ADD CONSTRAINT FK3E76S446RI8AS9K3CWDLH4MO9 
    FOREIGN KEY (PRGM_ID) 
    REFERENCES TB_BCM_PRGM;

ALTER TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP 
    ADD CONSTRAINT FKCEP99MAKY2VIAWCANAQ28WCQW 
    FOREIGN KEY (ELEMENT_SEQ) 
    REFERENCES TB_BCM_VIEW_ELEMENT;

ALTER TABLE TB_BCM_VIEW_ELEMENT_ROLE_MAP 
    ADD CONSTRAINT FKOPHSW4F873NLC276W3OCGR59E 
    FOREIGN KEY (ROLE_ID) 
    REFERENCES TB_BCM_ROLE;
